---

clone:
  git-clone:
    commands: |
      set -ex
      git clone -b ${DRONE_TAG:-$DRONE_BRANCH} $DRONE_REMOTE_URL .
      if [ x$DRONE_PULL_REQUEST != x ]; then
          git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
          EMAIL=ci git merge --no-edit FETCH_HEAD
      fi
      git rev-parse HEAD
    image: "blang/latex:ctanfull"

kind: pipeline
name: highway-latex

steps:
- name: build-pdf
  commands:
  - "pdflatex -halt-on-error highway && biber highway && pdflatex -halt-on-error highway && pdflatex -halt-on-error highway"
  image: "blang/latex:ctanfull"
  when:
    event:
    - pull_request
    - push
    branch:
    - master

trigger:
  branch:
  - master

---
kind: pipeline
name: highway-release-tag

steps:
- name: build-pdf-tag
  commands:
  - "pdflatex -halt-on-error highway && biber highway && pdflatex -halt-on-error highway && pdflatex -halt-on-error highway"
  image: "blang/latex:ctanfull"

- name: github_publish_release_artifacts
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    - md5
    files:
    - "highway.pdf"
    prerelease:
    - true
  image: plugins/github-release
  depends_on:
  - build-pdf-tag

trigger:
    ref:
    - refs/tags/v*
